#!/bin/bash -e

get_password() {
  password=$2
  if [ -z $password ]; then
    echo -n "$1: " >/dev/stderr
    read -s password
    echo > /dev/stderr
  fi
  echo $password
}

if [ -f .env ]; then
  . .env
fi

#APP_SECRET=`get_password "Murp.us secret" $APP_SECRET`

#heroku config:set "APP_SECRET=$APP_SECRET" >/dev/null
git remote add heroku https://git.heroku.com/murpus.git 2>/dev/null || :
git checkout prod
git add -u
git commit -m "commiting for deploy"
git push heroku prod:master
